# Generated by Django 4.1.3 on 2024-01-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='split_ratio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
